backend:
  name: github
  repo: DEIN_GITHUB_NAME/DEIN_REPO_NAME # Stelle sicher, dass hier z.B. julian/m-fleger-web steht!
  branch: main # Oder master
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog-Beiträge"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Vorschautext", name: "excerpt", widget: "string" }
      - { label: "Kategorien", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }
